# Generated by Django 2.0.13 on 2019-05-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
