# Generated by Django 2.0.13 on 2019-05-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_details_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
