# Generated by Django 2.0.13 on 2019-05-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Careers',
        ),
    ]
